package com.bridgelabz.demo.enumeration;

public enum Message {
	SUCCESSFUL, BAD_REQUEST, USER_ADDED, EMAIL_ID_ALREADY_EXISTS, CONFLICT, EMAIL_ID_DOESNT_EXISTS,
	USER_LOGGED_IN_SUCCESFULL, EMAIL_HAS_NOT_VERIFIED, ENTERED_WRONG_PASSWORD, EMAIL_SENT_SUCCESSFULLY, NOT_FOUND,
	TRY_AGAIN_LATER, SERVER_SIDE_PROBLEM, PASSWORD_UPDATED_SUCCESSFULLY_PLEASE_LOGIN_TO_CONTINUE, INVALID_USER,
	NOTE_ADDED_SUCCESFULLY, USER_ID_DOESNT_EXISTS
}
