package com.bridgelabz.demo.enumeration;

public enum Message {
	SUCCESSFUL, BAD_REQUEST, USER_ADDED, EMAIL_ID_ALREADY_EXISTS, CONFLICT, EMAIL_ID_DOESNT_EXISTS,
	USER_LOGGED_IN_SUCCESFULL, EMAIL_HAS_NOT_VERIFIED, ENTERED_WRONG_PASSWORD
}
